//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPD.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPD.Util.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] Footer_Zara_Template {
            get {
                object obj = ResourceManager.GetObject("Footer_Zara_Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ThermalLabel Version=&quot;5.0&quot; Width=&quot;10.2&quot; Height=&quot;4.5&quot; GapLength=&quot;0&quot; MarkLength=&quot;0&quot; OffsetLength=&quot;0&quot; UnitType=&quot;Cm&quot; LabelsPerRow=&quot;1&quot; LabelsHorizontalGapLength=&quot;0&quot; IsContinuous=&quot;False&quot;&gt;
        ///  &lt;Items&gt;
        ///    &lt;LineShapeItem Name=&quot;&quot; Y=&quot;1.4667&quot; DataField=&quot;&quot; DataFieldFormatString=&quot;&quot; CacheItemId=&quot;&quot; Comments=&quot;&quot; Tag=&quot;&quot; Width=&quot;10.2&quot; Height=&quot;0.0254&quot; StrokeThickness=&quot;0.0254&quot; /&gt;
        ///    &lt;LineShapeItem Name=&quot;&quot; Y=&quot;2.2667&quot; DataField=&quot;&quot; DataFieldFormatString=&quot;&quot; CacheItemId=&quot;&quot; Comments=&quot;&quot; Tag=&quot;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Zara_Template {
            get {
                return ResourceManager.GetString("Zara_Template", resourceCulture);
            }
        }
    }
}
