//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5472.
// 
#pragma warning disable 1591

namespace TransactionManual_CI.com.seur.citpre {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ImprimirECBWebServiceHttpBinding", Namespace="http://localhost:7026/ImprimirECBWebService")]
    public partial class ImprimirECBWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback serviciosProductosCIOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLogoImprOperationCompleted;
        
        private System.Threading.SendOrPostCallback impresionPDFWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback marcasModelosImpresorasWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback tramaImprCodBultoOperationCompleted;
        
        private System.Threading.SendOrPostCallback impresionConECBWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback configImprOperationCompleted;
        
        private System.Threading.SendOrPostCallback impresionWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback tramaImprOperationCompleted;
        
        private System.Threading.SendOrPostCallback impresionPDFConECBWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback configuracionImpresoraWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback impresionIntegracionConECBWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback serviciosComplementariosWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback impresionCodeBarWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback tramasImprEnvioOperationCompleted;
        
        private System.Threading.SendOrPostCallback impresionIntegracionPDFConECBWSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ImprimirECBWebService() {
            this.Url = global::TransactionManual_CI.Properties.Settings.Default.TransactionManual_CI_com_seur_citpre_ImprimirECBWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event serviciosProductosCICompletedEventHandler serviciosProductosCICompleted;
        
        /// <remarks/>
        public event getLogoImprCompletedEventHandler getLogoImprCompleted;
        
        /// <remarks/>
        public event impresionPDFWSCompletedEventHandler impresionPDFWSCompleted;
        
        /// <remarks/>
        public event marcasModelosImpresorasWSCompletedEventHandler marcasModelosImpresorasWSCompleted;
        
        /// <remarks/>
        public event tramaImprCodBultoCompletedEventHandler tramaImprCodBultoCompleted;
        
        /// <remarks/>
        public event impresionConECBWSCompletedEventHandler impresionConECBWSCompleted;
        
        /// <remarks/>
        public event configImprCompletedEventHandler configImprCompleted;
        
        /// <remarks/>
        public event impresionWSCompletedEventHandler impresionWSCompleted;
        
        /// <remarks/>
        public event tramaImprCompletedEventHandler tramaImprCompleted;
        
        /// <remarks/>
        public event impresionPDFConECBWSCompletedEventHandler impresionPDFConECBWSCompleted;
        
        /// <remarks/>
        public event configuracionImpresoraWSCompletedEventHandler configuracionImpresoraWSCompleted;
        
        /// <remarks/>
        public event impresionIntegracionConECBWSCompletedEventHandler impresionIntegracionConECBWSCompleted;
        
        /// <remarks/>
        public event serviciosComplementariosWSCompletedEventHandler serviciosComplementariosWSCompleted;
        
        /// <remarks/>
        public event impresionCodeBarWSCompletedEventHandler impresionCodeBarWSCompleted;
        
        /// <remarks/>
        public event tramasImprEnvioCompletedEventHandler tramasImprEnvioCompleted;
        
        /// <remarks/>
        public event impresionIntegracionPDFConECBWSCompletedEventHandler impresionIntegracionPDFConECBWSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string serviciosProductosCI([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("serviciosProductosCI", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void serviciosProductosCIAsync(string in0, string in1, string in2) {
            this.serviciosProductosCIAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void serviciosProductosCIAsync(string in0, string in1, string in2, object userState) {
            if ((this.serviciosProductosCIOperationCompleted == null)) {
                this.serviciosProductosCIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnserviciosProductosCIOperationCompleted);
            }
            this.InvokeAsync("serviciosProductosCI", new object[] {
                        in0,
                        in1,
                        in2}, this.serviciosProductosCIOperationCompleted, userState);
        }
        
        private void OnserviciosProductosCIOperationCompleted(object arg) {
            if ((this.serviciosProductosCICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.serviciosProductosCICompleted(this, new serviciosProductosCICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getLogoImpr([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("getLogoImpr", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getLogoImprAsync(string in0, System.Nullable<int> in1, System.Nullable<int> in2, string in3) {
            this.getLogoImprAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void getLogoImprAsync(string in0, System.Nullable<int> in1, System.Nullable<int> in2, string in3, object userState) {
            if ((this.getLogoImprOperationCompleted == null)) {
                this.getLogoImprOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLogoImprOperationCompleted);
            }
            this.InvokeAsync("getLogoImpr", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.getLogoImprOperationCompleted, userState);
        }
        
        private void OngetLogoImprOperationCompleted(object arg) {
            if ((this.getLogoImprCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLogoImprCompleted(this, new getLogoImprCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string impresionPDFWS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("impresionPDFWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void impresionPDFWSAsync(string in0, string in1, string in2, string in3) {
            this.impresionPDFWSAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void impresionPDFWSAsync(string in0, string in1, string in2, string in3, object userState) {
            if ((this.impresionPDFWSOperationCompleted == null)) {
                this.impresionPDFWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimpresionPDFWSOperationCompleted);
            }
            this.InvokeAsync("impresionPDFWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.impresionPDFWSOperationCompleted, userState);
        }
        
        private void OnimpresionPDFWSOperationCompleted(object arg) {
            if ((this.impresionPDFWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.impresionPDFWSCompleted(this, new impresionPDFWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string marcasModelosImpresorasWS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("marcasModelosImpresorasWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void marcasModelosImpresorasWSAsync(string in0, string in1, string in2, string in3) {
            this.marcasModelosImpresorasWSAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void marcasModelosImpresorasWSAsync(string in0, string in1, string in2, string in3, object userState) {
            if ((this.marcasModelosImpresorasWSOperationCompleted == null)) {
                this.marcasModelosImpresorasWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmarcasModelosImpresorasWSOperationCompleted);
            }
            this.InvokeAsync("marcasModelosImpresorasWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.marcasModelosImpresorasWSOperationCompleted, userState);
        }
        
        private void OnmarcasModelosImpresorasWSOperationCompleted(object arg) {
            if ((this.marcasModelosImpresorasWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.marcasModelosImpresorasWSCompleted(this, new marcasModelosImpresorasWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string tramaImprCodBulto([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in7) {
            object[] results = this.Invoke("tramaImprCodBulto", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tramaImprCodBultoAsync(string in0, string in1, string in2, string in3, string in4, System.Nullable<int> in5, System.Nullable<int> in6, string in7) {
            this.tramaImprCodBultoAsync(in0, in1, in2, in3, in4, in5, in6, in7, null);
        }
        
        /// <remarks/>
        public void tramaImprCodBultoAsync(string in0, string in1, string in2, string in3, string in4, System.Nullable<int> in5, System.Nullable<int> in6, string in7, object userState) {
            if ((this.tramaImprCodBultoOperationCompleted == null)) {
                this.tramaImprCodBultoOperationCompleted = new System.Threading.SendOrPostCallback(this.OntramaImprCodBultoOperationCompleted);
            }
            this.InvokeAsync("tramaImprCodBulto", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7}, this.tramaImprCodBultoOperationCompleted, userState);
        }
        
        private void OntramaImprCodBultoOperationCompleted(object arg) {
            if ((this.tramaImprCodBultoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tramaImprCodBultoCompleted(this, new tramaImprCodBultoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public ResponseImprConECBWS impresionConECBWS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in6) {
            object[] results = this.Invoke("impresionConECBWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6});
            return ((ResponseImprConECBWS)(results[0]));
        }
        
        /// <remarks/>
        public void impresionConECBWSAsync(string in0, string in1, string in2, string in3, string in4, string in5, string in6) {
            this.impresionConECBWSAsync(in0, in1, in2, in3, in4, in5, in6, null);
        }
        
        /// <remarks/>
        public void impresionConECBWSAsync(string in0, string in1, string in2, string in3, string in4, string in5, string in6, object userState) {
            if ((this.impresionConECBWSOperationCompleted == null)) {
                this.impresionConECBWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimpresionConECBWSOperationCompleted);
            }
            this.InvokeAsync("impresionConECBWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6}, this.impresionConECBWSOperationCompleted, userState);
        }
        
        private void OnimpresionConECBWSOperationCompleted(object arg) {
            if ((this.impresionConECBWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.impresionConECBWSCompleted(this, new impresionConECBWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string configImpr([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in6) {
            object[] results = this.Invoke("configImpr", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void configImprAsync(string in0, string in1, string in2, string in3, System.Nullable<int> in4, System.Nullable<int> in5, string in6) {
            this.configImprAsync(in0, in1, in2, in3, in4, in5, in6, null);
        }
        
        /// <remarks/>
        public void configImprAsync(string in0, string in1, string in2, string in3, System.Nullable<int> in4, System.Nullable<int> in5, string in6, object userState) {
            if ((this.configImprOperationCompleted == null)) {
                this.configImprOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfigImprOperationCompleted);
            }
            this.InvokeAsync("configImpr", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6}, this.configImprOperationCompleted, userState);
        }
        
        private void OnconfigImprOperationCompleted(object arg) {
            if ((this.configImprCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.configImprCompleted(this, new configImprCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string impresionWS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in6) {
            object[] results = this.Invoke("impresionWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void impresionWSAsync(string in0, string in1, string in2, string in3, string in4, string in5, string in6) {
            this.impresionWSAsync(in0, in1, in2, in3, in4, in5, in6, null);
        }
        
        /// <remarks/>
        public void impresionWSAsync(string in0, string in1, string in2, string in3, string in4, string in5, string in6, object userState) {
            if ((this.impresionWSOperationCompleted == null)) {
                this.impresionWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimpresionWSOperationCompleted);
            }
            this.InvokeAsync("impresionWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6}, this.impresionWSOperationCompleted, userState);
        }
        
        private void OnimpresionWSOperationCompleted(object arg) {
            if ((this.impresionWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.impresionWSCompleted(this, new impresionWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string tramaImpr([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in7) {
            object[] results = this.Invoke("tramaImpr", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tramaImprAsync(string in0, string in1, string in2, string in3, string in4, System.Nullable<int> in5, System.Nullable<int> in6, string in7) {
            this.tramaImprAsync(in0, in1, in2, in3, in4, in5, in6, in7, null);
        }
        
        /// <remarks/>
        public void tramaImprAsync(string in0, string in1, string in2, string in3, string in4, System.Nullable<int> in5, System.Nullable<int> in6, string in7, object userState) {
            if ((this.tramaImprOperationCompleted == null)) {
                this.tramaImprOperationCompleted = new System.Threading.SendOrPostCallback(this.OntramaImprOperationCompleted);
            }
            this.InvokeAsync("tramaImpr", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7}, this.tramaImprOperationCompleted, userState);
        }
        
        private void OntramaImprOperationCompleted(object arg) {
            if ((this.tramaImprCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tramaImprCompleted(this, new tramaImprCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public ResponseImprPDFConECBWS impresionPDFConECBWS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("impresionPDFConECBWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((ResponseImprPDFConECBWS)(results[0]));
        }
        
        /// <remarks/>
        public void impresionPDFConECBWSAsync(string in0, string in1, string in2, string in3) {
            this.impresionPDFConECBWSAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void impresionPDFConECBWSAsync(string in0, string in1, string in2, string in3, object userState) {
            if ((this.impresionPDFConECBWSOperationCompleted == null)) {
                this.impresionPDFConECBWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimpresionPDFConECBWSOperationCompleted);
            }
            this.InvokeAsync("impresionPDFConECBWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.impresionPDFConECBWSOperationCompleted, userState);
        }
        
        private void OnimpresionPDFConECBWSOperationCompleted(object arg) {
            if ((this.impresionPDFConECBWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.impresionPDFConECBWSCompleted(this, new impresionPDFConECBWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string configuracionImpresoraWS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in5) {
            object[] results = this.Invoke("configuracionImpresoraWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void configuracionImpresoraWSAsync(string in0, string in1, string in2, string in3, string in4, string in5) {
            this.configuracionImpresoraWSAsync(in0, in1, in2, in3, in4, in5, null);
        }
        
        /// <remarks/>
        public void configuracionImpresoraWSAsync(string in0, string in1, string in2, string in3, string in4, string in5, object userState) {
            if ((this.configuracionImpresoraWSOperationCompleted == null)) {
                this.configuracionImpresoraWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfiguracionImpresoraWSOperationCompleted);
            }
            this.InvokeAsync("configuracionImpresoraWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5}, this.configuracionImpresoraWSOperationCompleted, userState);
        }
        
        private void OnconfiguracionImpresoraWSOperationCompleted(object arg) {
            if ((this.configuracionImpresoraWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.configuracionImpresoraWSCompleted(this, new configuracionImpresoraWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public ResponseImprConECBWS impresionIntegracionConECBWS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in7, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in8, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in9, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in10) {
            object[] results = this.Invoke("impresionIntegracionConECBWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7,
                        in8,
                        in9,
                        in10});
            return ((ResponseImprConECBWS)(results[0]));
        }
        
        /// <remarks/>
        public void impresionIntegracionConECBWSAsync(string in0, string in1, string in2, string in3, string in4, string in5, string in6, string in7, System.Nullable<int> in8, System.Nullable<int> in9, string in10) {
            this.impresionIntegracionConECBWSAsync(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, null);
        }
        
        /// <remarks/>
        public void impresionIntegracionConECBWSAsync(string in0, string in1, string in2, string in3, string in4, string in5, string in6, string in7, System.Nullable<int> in8, System.Nullable<int> in9, string in10, object userState) {
            if ((this.impresionIntegracionConECBWSOperationCompleted == null)) {
                this.impresionIntegracionConECBWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimpresionIntegracionConECBWSOperationCompleted);
            }
            this.InvokeAsync("impresionIntegracionConECBWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7,
                        in8,
                        in9,
                        in10}, this.impresionIntegracionConECBWSOperationCompleted, userState);
        }
        
        private void OnimpresionIntegracionConECBWSOperationCompleted(object arg) {
            if ((this.impresionIntegracionConECBWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.impresionIntegracionConECBWSCompleted(this, new impresionIntegracionConECBWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string serviciosComplementariosWS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4) {
            object[] results = this.Invoke("serviciosComplementariosWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void serviciosComplementariosWSAsync(string in0, string in1, System.Nullable<int> in2, System.Nullable<int> in3, string in4) {
            this.serviciosComplementariosWSAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void serviciosComplementariosWSAsync(string in0, string in1, System.Nullable<int> in2, System.Nullable<int> in3, string in4, object userState) {
            if ((this.serviciosComplementariosWSOperationCompleted == null)) {
                this.serviciosComplementariosWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnserviciosComplementariosWSOperationCompleted);
            }
            this.InvokeAsync("serviciosComplementariosWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.serviciosComplementariosWSOperationCompleted, userState);
        }
        
        private void OnserviciosComplementariosWSOperationCompleted(object arg) {
            if ((this.serviciosComplementariosWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.serviciosComplementariosWSCompleted(this, new serviciosComplementariosWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string impresionCodeBarWS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in6) {
            object[] results = this.Invoke("impresionCodeBarWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void impresionCodeBarWSAsync(string in0, string in1, System.Nullable<int> in2, string in3, System.Nullable<int> in4, System.Nullable<int> in5, string in6) {
            this.impresionCodeBarWSAsync(in0, in1, in2, in3, in4, in5, in6, null);
        }
        
        /// <remarks/>
        public void impresionCodeBarWSAsync(string in0, string in1, System.Nullable<int> in2, string in3, System.Nullable<int> in4, System.Nullable<int> in5, string in6, object userState) {
            if ((this.impresionCodeBarWSOperationCompleted == null)) {
                this.impresionCodeBarWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimpresionCodeBarWSOperationCompleted);
            }
            this.InvokeAsync("impresionCodeBarWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6}, this.impresionCodeBarWSOperationCompleted, userState);
        }
        
        private void OnimpresionCodeBarWSOperationCompleted(object arg) {
            if ((this.impresionCodeBarWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.impresionCodeBarWSCompleted(this, new impresionCodeBarWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string tramasImprEnvio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in7) {
            object[] results = this.Invoke("tramasImprEnvio", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tramasImprEnvioAsync(string in0, string in1, string in2, string in3, string in4, System.Nullable<int> in5, System.Nullable<int> in6, string in7) {
            this.tramasImprEnvioAsync(in0, in1, in2, in3, in4, in5, in6, in7, null);
        }
        
        /// <remarks/>
        public void tramasImprEnvioAsync(string in0, string in1, string in2, string in3, string in4, System.Nullable<int> in5, System.Nullable<int> in6, string in7, object userState) {
            if ((this.tramasImprEnvioOperationCompleted == null)) {
                this.tramasImprEnvioOperationCompleted = new System.Threading.SendOrPostCallback(this.OntramasImprEnvioOperationCompleted);
            }
            this.InvokeAsync("tramasImprEnvio", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7}, this.tramasImprEnvioOperationCompleted, userState);
        }
        
        private void OntramasImprEnvioOperationCompleted(object arg) {
            if ((this.tramasImprEnvioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tramasImprEnvioCompleted(this, new tramasImprEnvioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://localhost:7026/ImprimirECBWebService", ResponseNamespace="http://localhost:7026/ImprimirECBWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public ResponseImprPDFConECBWS impresionIntegracionPDFConECBWS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in7) {
            object[] results = this.Invoke("impresionIntegracionPDFConECBWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7});
            return ((ResponseImprPDFConECBWS)(results[0]));
        }
        
        /// <remarks/>
        public void impresionIntegracionPDFConECBWSAsync(string in0, string in1, string in2, string in3, string in4, System.Nullable<int> in5, System.Nullable<int> in6, string in7) {
            this.impresionIntegracionPDFConECBWSAsync(in0, in1, in2, in3, in4, in5, in6, in7, null);
        }
        
        /// <remarks/>
        public void impresionIntegracionPDFConECBWSAsync(string in0, string in1, string in2, string in3, string in4, System.Nullable<int> in5, System.Nullable<int> in6, string in7, object userState) {
            if ((this.impresionIntegracionPDFConECBWSOperationCompleted == null)) {
                this.impresionIntegracionPDFConECBWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimpresionIntegracionPDFConECBWSOperationCompleted);
            }
            this.InvokeAsync("impresionIntegracionPDFConECBWS", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7}, this.impresionIntegracionPDFConECBWSOperationCompleted, userState);
        }
        
        private void OnimpresionIntegracionPDFConECBWSOperationCompleted(object arg) {
            if ((this.impresionIntegracionPDFConECBWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.impresionIntegracionPDFConECBWSCompleted(this, new impresionIntegracionPDFConECBWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.val.cit.seur.com")]
    public partial class ResponseImprConECBWS {
        
        private string[] eCBField;
        
        private string mensajeField;
        
        private string trazaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://localhost:7026/ImprimirECBWebService")]
        public string[] ECB {
            get {
                return this.eCBField;
            }
            set {
                this.eCBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string traza {
            get {
                return this.trazaField;
            }
            set {
                this.trazaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.val.cit.seur.com")]
    public partial class ResponseImprPDFConECBWS {
        
        private string[] eCBField;
        
        private string pDFField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://localhost:7026/ImprimirECBWebService")]
        public string[] ECB {
            get {
                return this.eCBField;
            }
            set {
                this.eCBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PDF {
            get {
                return this.pDFField;
            }
            set {
                this.pDFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void serviciosProductosCICompletedEventHandler(object sender, serviciosProductosCICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class serviciosProductosCICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal serviciosProductosCICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getLogoImprCompletedEventHandler(object sender, getLogoImprCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLogoImprCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLogoImprCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void impresionPDFWSCompletedEventHandler(object sender, impresionPDFWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class impresionPDFWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal impresionPDFWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void marcasModelosImpresorasWSCompletedEventHandler(object sender, marcasModelosImpresorasWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class marcasModelosImpresorasWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal marcasModelosImpresorasWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void tramaImprCodBultoCompletedEventHandler(object sender, tramaImprCodBultoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tramaImprCodBultoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tramaImprCodBultoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void impresionConECBWSCompletedEventHandler(object sender, impresionConECBWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class impresionConECBWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal impresionConECBWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseImprConECBWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseImprConECBWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void configImprCompletedEventHandler(object sender, configImprCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class configImprCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal configImprCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void impresionWSCompletedEventHandler(object sender, impresionWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class impresionWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal impresionWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void tramaImprCompletedEventHandler(object sender, tramaImprCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tramaImprCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tramaImprCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void impresionPDFConECBWSCompletedEventHandler(object sender, impresionPDFConECBWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class impresionPDFConECBWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal impresionPDFConECBWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseImprPDFConECBWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseImprPDFConECBWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void configuracionImpresoraWSCompletedEventHandler(object sender, configuracionImpresoraWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class configuracionImpresoraWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal configuracionImpresoraWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void impresionIntegracionConECBWSCompletedEventHandler(object sender, impresionIntegracionConECBWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class impresionIntegracionConECBWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal impresionIntegracionConECBWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseImprConECBWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseImprConECBWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void serviciosComplementariosWSCompletedEventHandler(object sender, serviciosComplementariosWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class serviciosComplementariosWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal serviciosComplementariosWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void impresionCodeBarWSCompletedEventHandler(object sender, impresionCodeBarWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class impresionCodeBarWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal impresionCodeBarWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void tramasImprEnvioCompletedEventHandler(object sender, tramasImprEnvioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tramasImprEnvioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tramasImprEnvioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void impresionIntegracionPDFConECBWSCompletedEventHandler(object sender, impresionIntegracionPDFConECBWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class impresionIntegracionPDFConECBWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal impresionIntegracionPDFConECBWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseImprPDFConECBWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseImprPDFConECBWS)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591